/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

float *
add_1_svc(input *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = argp->num1+argp->num2;
	printf("add(%f, %f) is called\n", argp->num1, argp->num2);

	return &result;
}

float *
sub_1_svc(input *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = argp->num1-argp->num2;
	printf("sub(%f, %f) is called\n", argp->num1, argp->num2);

	return &result;
}

float *
mul_1_svc(input *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = argp->num1*argp->num2;
	printf("mul(%f, %f) is called\n", argp->num1, argp->num2);

	return &result;
}

float *
div_1_svc(input *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */
	result = argp->num1/argp->num2;
	printf("div(%f, %f) is called\n", argp->num1, argp->num2);

	return &result;
}
