/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calc_prog_1(char *host, float num1, float num2, char op)
{
	CLIENT *clnt;
	float  *result_1;
	input  add_1_arg;
	float  *result_2;
	input  sub_1_arg;
	float  *result_3;
	input  mul_1_arg;
	float  *result_4;
	input  div_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROG, CALC_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	if(op == '+') {
		add_1_arg.num1=num1;
		add_1_arg.num2=num2;
		add_1_arg.op=op;
		result_1 = add_1(&add_1_arg, clnt);
		if (result_1 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else {
			printf("%f\n",*result_1);
		}
	}
	if(op == '-') {
		sub_1_arg.num1=num1;
		sub_1_arg.num2=num2;
		sub_1_arg.op=op;
		result_2 = sub_1(&sub_1_arg, clnt);
		if (result_2 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else {
			printf("%f\n",*result_2);
		}
	}
	if(op == 'm') {
		mul_1_arg.num1=num1;
		mul_1_arg.num2=num2;
		mul_1_arg.op=op;
		result_3 = mul_1(&mul_1_arg, clnt);
		if (result_3 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else {
			printf("%f\n",*result_3);
		}
	}
	if(op == '/') {
		div_1_arg.num1=num1;
		div_1_arg.num2=num2;
		div_1_arg.op=op;
		result_4 = div_1(&div_1_arg, clnt);
		if (result_4 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else {
			printf("%f\n",*result_4);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 4) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calc_prog_1 (host, atoi(argv[2]), atoi(argv[3]), argv[4][0]);
exit (0);
}
