/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input {
	float num1;
	float num2;
	char op;
};
typedef struct input input;

#define CALC_PROG 0x2fffffff
#define CALC_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  float * add_1(input *, CLIENT *);
extern  float * add_1_svc(input *, struct svc_req *);
#define sub 2
extern  float * sub_1(input *, CLIENT *);
extern  float * sub_1_svc(input *, struct svc_req *);
#define mul 3
extern  float * mul_1(input *, CLIENT *);
extern  float * mul_1_svc(input *, struct svc_req *);
#define div 4
extern  float * div_1(input *, CLIENT *);
extern  float * div_1_svc(input *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add 1
extern  float * add_1();
extern  float * add_1_svc();
#define sub 2
extern  float * sub_1();
extern  float * sub_1_svc();
#define mul 3
extern  float * mul_1();
extern  float * mul_1_svc();
#define div 4
extern  float * div_1();
extern  float * div_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input (XDR *, input*);

#else /* K&R C */
extern bool_t xdr_input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
