/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TIME_H_RPCGEN
#define _TIME_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define GET_DATE_TIME_PROG 0x4562877
#define GET_DATE_TIME_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_DATE_TIME 1
extern  char ** get_date_time_1(void *, CLIENT *);
extern  char ** get_date_time_1_svc(void *, struct svc_req *);
extern int get_date_time_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_DATE_TIME 1
extern  char ** get_date_time_1();
extern  char ** get_date_time_1_svc();
extern int get_date_time_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TIME_H_RPCGEN */
